In [ ]:
DATA PREPARETION

In [ ]:
import pandas as pd
data = pd.read_csv('IRIS.csv')
print(data)

In [4]:
selected_columns = data[['sepal_length','sepal_width']]
print(selected_columns)

     sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]


In [5]:
filtered_data = data[data['sepal_length']>5]
print(filtered_data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
5             5.4          3.9           1.7          0.4     Iris-setosa
10            5.4          3.7           1.5          0.2     Iris-setosa
14            5.8          4.0           1.2          0.2     Iris-setosa
15            5.7          4.4           1.5          0.4     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[118 rows x 5 columns]


In [14]:
grouped_data = data.groupby('species')['petal_length'].sum()
print(grouped_data)

species
Iris-setosa         73.2
Iris-versicolor    213.0
Iris-virginica     277.6
Name: petal_length, dtype: float64


In [18]:
data1 = pd.read_csv('IRIS.csv')
data2 = pd.read_csv('IRIS.csv')
merged_data = pd.merge(data1,data2,on = 'sepal_length')
print(merged_data)

     sepal_length  sepal_width_x  petal_length_x  petal_width_x  \
0             5.1            3.5             1.4            0.2   
1             5.1            3.5             1.4            0.2   
2             5.1            3.5             1.4            0.2   
3             5.1            3.5             1.4            0.2   
4             5.1            3.5             1.4            0.2   
..            ...            ...             ...            ...   
895           7.7            3.0             6.1            2.3   
896           7.7            3.0             6.1            2.3   
897           7.7            3.0             6.1            2.3   
898           7.4            2.8             6.1            1.9   
899           7.9            3.8             6.4            2.0   

          species_x  sepal_width_y  petal_length_y  petal_width_y  \
0       Iris-setosa            3.5             1.4            0.2   
1       Iris-setosa            3.5             1.4       

In [19]:
data = pd.read_csv('IRIS.csv')
data.fillna(0,inplace = True)
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [23]:
def process_value(value):
    processed_value = value*2
    return processed_value
data['processed_column'] = data['sepal_length'].apply(process_value)
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

     processed_column  
0                10.2  
1                 9.8  
2  

In [33]:
pivot_table=pd.pivot_table(data,values="sepal_length",index="sepal_width",columns="species")
print(pivot_table)

species      Iris-setosa  Iris-versicolor  Iris-virginica
sepal_width                                              
2.0                  NaN         5.000000             NaN
2.2                  NaN         6.100000        6.000000
2.3             4.500000         5.600000             NaN
2.4                  NaN         5.300000             NaN
2.5                  NaN         5.625000        5.900000
2.6                  NaN         5.666667        6.900000
2.7                  NaN         5.680000        6.075000
2.8                  NaN         6.150000        6.475000
2.9             4.400000         6.085714        6.800000
3.0             4.700000         5.950000        6.716667
3.1             4.820000         6.766667        6.725000
3.2             4.680000         6.433333        6.760000
3.3             5.050000         6.300000        6.566667
3.4             5.033333         6.000000        6.250000
3.5             5.150000              NaN             NaN
3.6           

In [42]:
data['date_column'] = pd.to_datetime(data['sepal_length'])
data.set_index('date_column',inplace=True)
resampled_data = data.resample('M').sum()
print(resampled_data)

             sepal_length  sepal_width  petal_length  petal_width  \
date_column                                                         
1970-01-31          876.5        458.1         563.8        179.8   

             processed_column  
date_column                    
1970-01-31             1753.0  


# Using numpy

In [46]:
import numpy as np
arr= np.array([2,3,4,5,6,7])
print(arr)
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

[2 3 4 5 6 7]
27
4.5
7
2


In [47]:
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)

[[2 3 4]
 [5 6 7]]


In [50]:
arr = np.random.random((3,3))
print(arr)

[[0.12246886 0.77297161 0.00444916]
 [0.35509169 0.60076087 0.04030067]
 [0.13817106 0.44797891 0.4701703 ]]


In [51]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1 + arr2
print(result)

[5 7 9]


In [57]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
sum_along_rows = np.sum(arr4,axis=0)
sum_along_column = np.sum(arr4,axis=1)
print(sum_along_rows)
print(sum_along_column)

[12 15 18]
[ 6 15 24]


In [64]:
arr= np.array([2,3,4,5,6,7])
mask = arr > 5
filtered_data = arr[mask]
print(filtered_data)
print(arr)

[6 7]
[2 3 4 5 6 7]


In [68]:
arr= np.array([2,3,4,4,5,2,4,7,6,7])
unique_arr = np.unique(arr)
element_count = np.bincount(arr)
print(unique_arr)
print(element_count)


[2 3 4 5 6 7]
[0 0 2 1 3 1 1 2]


In [70]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
coefficients = np.polyfit(x,y,1)
slope,intercept = coefficients
print("slope:",slope)
print("intercept:",intercept)

slope: 1.0000000000000002
intercept: 4.999999999999999
